apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: luminateassortment.azurecr.io/app:latest
        imagePullPolicy: Always
        ports:
           - name: http
             containerPort: 8080
      imagePullSecrets:
      - name: lapoc-auth
---
apiVersion: v1
kind: Service
metadata:
 name: app-backend
spec:
 type: ClusterIP
 selector:
   app: app
 ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - app.centralus.cloudapp.azure.com
    secretName: app-tls
  rules:
  - host: app.centralus.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: app-backend
          servicePort: 80